Repository miltonarce/veton, pull requests merged in 2019-09, with the labels that each got.

#3 Feat/linter prettier
  front/.editorconfig
  front/.eslintrc.js
  front/.prettierignore
  front/.prettierrc
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/index.css
  front/src/serviceWorker.js
Labels: Frontend, enhancement

#6 BackAltaHistoriaClinicaMascotaUsuarioVeterinario-B09---AgregoSeedsDeRo
  back/app/Http/Controllers/API/ClinicalHistoriesController.php
  back/app/Http/Controllers/API/PetsController.php
  back/app/Models/ClinicalHistory.php
  back/app/Models/Pet.php
  back/database/migrations/2019_09_16_233950_create_gender_table.php
  back/database/seeds/BreedsTableSeeder.php
  back/database/seeds/ClinicalHistoriesTableSeeder.php
  back/database/seeds/ConsultationsTableSeeder.php
  back/database/seeds/DatabaseSeeder.php
  back/database/seeds/GenderTableSeeder.php
  back/database/seeds/PetsTableSeeder.php
  back/database/seeds/ProfilesTableSeeder.php
  back/database/seeds/TypesTableSeeder.php
  back/database/seeds/UsersTableSeeder.php
  back/database/seeds/VeterinariesTableSeeder.php
  back/routes/api.php
Labels: Backend, enhancement

#8 feat: create pet
  front/src/components/Alert/index.jsx
  front/src/components/FormPet/index.jsx
  front/src/components/FormPet/index.scss
  front/src/services/Api.js
  front/src/views/Home/index.jsx
Labels: Frontend, enhancement

#7 feat: add react-router with header,footer,main
  front/.gitignore
  front/package.json
  front/public/assets/logo.svg
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/src/App.css
  front/src/App.js
  front/src/App.scss
  front/src/components/Alert/index.jsx
  front/src/components/FormPet/index.jsx
  front/src/components/FormPet/index.scss
  front/src/components/shared/Footer/index.jsx
  front/src/components/shared/Footer/index.scss
  front/src/components/shared/Header/index.jsx
  front/src/components/shared/Header/index.scss
  front/src/components/shared/Main/index.jsx
  front/src/index.js
  front/src/services/Api.js
  front/src/views/Contact/index.jsx
  front/src/views/Contact/index.scss
  front/src/views/Home/index.jsx
  front/src/views/Home/index.scss
Labels: Frontend, enhancement

#19 fix: migrations gendersrollback, databaseSeeder
  back/apiveton/database/migrations/2019_09_16_233950_create_genders_table.php
  back/apiveton/database/seeds/DatabaseSeeder.php
Labels: Backend

#21 #45BackAltaNuevaConsulta
  back/apiveton/app/Http/Controllers/Api/ConsultationsController.php
  back/apiveton/app/Models/Consultation.php
  back/apiveton/routes/api.php
Labels: Backend
